// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260308224711_AddJobPositionEntity")]
    partial class AddJobPositionEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.JobPositions.JobPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("HourlyCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("hourly_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_job_positions");

                    b.ToTable("job_positions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Permissions.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5037d95-d672-4bdf-80ea-c22bc687e85f"),
                            Code = "User.Create",
                            Description = "Permite crear nuevos usuarios en el sistema",
                            Name = "Crear Usuario"
                        },
                        new
                        {
                            Id = new Guid("4604fa93-c900-4b6e-aad2-1f424a4d3f01"),
                            Code = "User.Read",
                            Description = "Permite ver información de usuarios",
                            Name = "Ver Usuario"
                        },
                        new
                        {
                            Id = new Guid("d14e36b8-f5b7-454b-91dd-714901ce54d2"),
                            Code = "User.Update",
                            Description = "Permite actualizar información de usuarios",
                            Name = "Actualizar Usuario"
                        },
                        new
                        {
                            Id = new Guid("17c86b19-c4b0-4596-a016-cb568a343367"),
                            Code = "User.Delete",
                            Description = "Permite eliminar usuarios del sistema",
                            Name = "Eliminar Usuario"
                        },
                        new
                        {
                            Id = new Guid("87c67f54-568a-4cbf-8992-05b4cfa20b0c"),
                            Code = "Role.Create",
                            Description = "Permite crear nuevos roles en el sistema",
                            Name = "Crear Rol"
                        },
                        new
                        {
                            Id = new Guid("1d8c3417-2833-42e2-9338-2ed2ba5a3290"),
                            Code = "Role.Read",
                            Description = "Permite ver información de roles",
                            Name = "Ver Rol"
                        },
                        new
                        {
                            Id = new Guid("283a2cc6-3e80-41ca-90f7-227f7bcefe4c"),
                            Code = "Role.Update",
                            Description = "Permite actualizar información de roles",
                            Name = "Actualizar Rol"
                        },
                        new
                        {
                            Id = new Guid("8e958e23-2110-4798-b6ac-f04dd0dd156d"),
                            Code = "Role.Delete",
                            Description = "Permite eliminar roles del sistema",
                            Name = "Eliminar Rol"
                        },
                        new
                        {
                            Id = new Guid("b8f1a9d4-e5c2-4a7b-9f3e-1d6c8a4b2e5f"),
                            Code = "Product.Create",
                            Description = "Permite crear nuevos productos en el sistema",
                            Name = "Crear Producto"
                        },
                        new
                        {
                            Id = new Guid("c9e2b8f5-d6a3-4b8c-a0f4-2e7d9b5c3f6a"),
                            Code = "Product.Read",
                            Description = "Permite ver información de productos",
                            Name = "Ver Producto"
                        },
                        new
                        {
                            Id = new Guid("d0f3c9a6-e7b4-4c9d-b1e5-3f8e0c6d4a7b"),
                            Code = "Product.Update",
                            Description = "Permite actualizar información de productos",
                            Name = "Actualizar Producto"
                        },
                        new
                        {
                            Id = new Guid("e1a4d0b7-f8c5-4d0e-c2f6-4a9f1d7e5b8c"),
                            Code = "Product.Delete",
                            Description = "Permite eliminar productos del sistema",
                            Name = "Eliminar Producto"
                        },
                        new
                        {
                            Id = new Guid("f2b5e1c8-a9d6-4e3f-b7a0-5c8d1e9f2a6b"),
                            Code = "Category.Create",
                            Description = "Permite crear nuevas categorías en el sistema",
                            Name = "Crear Categoría"
                        },
                        new
                        {
                            Id = new Guid("a3c6f2d9-b0e7-4f8a-c1b4-6d9e2f0a3b7c"),
                            Code = "Category.Read",
                            Description = "Permite ver información de categorías",
                            Name = "Ver Categoría"
                        },
                        new
                        {
                            Id = new Guid("b4d7a3e0-c1f8-4a9b-d2c5-7e0f3a1b4c8d"),
                            Code = "Category.Update",
                            Description = "Permite actualizar información de categorías",
                            Name = "Actualizar Categoría"
                        },
                        new
                        {
                            Id = new Guid("c5e8b4f1-d2a9-4b0c-e3d6-8f1a4b2c5d9e"),
                            Code = "Category.Delete",
                            Description = "Permite eliminar categorías del sistema",
                            Name = "Eliminar Categoría"
                        },
                        new
                        {
                            Id = new Guid("b0d3a9e6-c7f4-4a5b-d8c1-3e6f9a7b0c4d"),
                            Code = "ProductOption.Create",
                            Description = "Permite crear nuevas opciones de producto",
                            Name = "Crear Opción de Producto"
                        },
                        new
                        {
                            Id = new Guid("c1e4b0f7-d8a5-4b6c-e9d2-4f7a0b8c1d5e"),
                            Code = "ProductOption.Read",
                            Description = "Permite ver información de opciones de producto",
                            Name = "Ver Opción de Producto"
                        },
                        new
                        {
                            Id = new Guid("d2f5c1a8-e9b6-4c7d-f0e3-5a8b1c9d2e6f"),
                            Code = "ProductOption.Update",
                            Description = "Permite actualizar opciones de producto",
                            Name = "Actualizar Opción de Producto"
                        },
                        new
                        {
                            Id = new Guid("e3a6d2b9-f0c7-4d8e-a1f4-6b9c2d0e3f7a"),
                            Code = "ProductOption.Delete",
                            Description = "Permite eliminar opciones de producto",
                            Name = "Eliminar Opción de Producto"
                        },
                        new
                        {
                            Id = new Guid("d8f1a4b5-e2c9-4d3e-f6a7-1b0c5d8e3f9a"),
                            Code = "Option.Create",
                            Description = "Permite crear nuevas opciones en el sistema",
                            Name = "Crear Opción"
                        },
                        new
                        {
                            Id = new Guid("e9a2b5c6-f3d0-4e4f-a7b8-2c1d6e9f4a0b"),
                            Code = "Option.Read",
                            Description = "Permite ver información de opciones",
                            Name = "Ver Opción"
                        },
                        new
                        {
                            Id = new Guid("f0b3c6d7-a4e1-4f5a-b8c9-3d2e7f0a5b1c"),
                            Code = "Option.Update",
                            Description = "Permite actualizar opciones del sistema",
                            Name = "Actualizar Opción"
                        },
                        new
                        {
                            Id = new Guid("a1c4d7e8-b5f2-4a6b-c9d0-4e3f8a1b6c2d"),
                            Code = "Option.Delete",
                            Description = "Permite eliminar opciones del sistema",
                            Name = "Eliminar Opción"
                        },
                        new
                        {
                            Id = new Guid("f4b7e3c0-a1d8-4e9f-b2a5-7c0d3e1f4a8b"),
                            Code = "Ingredient.Create",
                            Description = "Permite crear nuevos ingredientes en el sistema",
                            Name = "Crear Ingrediente"
                        },
                        new
                        {
                            Id = new Guid("a5c8f4d1-b2e9-4f0a-c3b6-8d1e4f2a5b9c"),
                            Code = "Ingredient.Read",
                            Description = "Permite ver información de ingredientes",
                            Name = "Ver Ingrediente"
                        },
                        new
                        {
                            Id = new Guid("b6d9a5e2-c3f0-4a1b-d4c7-9e2f5a3b6c0d"),
                            Code = "Ingredient.Update",
                            Description = "Permite actualizar información de ingredientes",
                            Name = "Actualizar Ingrediente"
                        },
                        new
                        {
                            Id = new Guid("c7e0b6f3-d4a1-4b2c-e5d8-0f3a6b4c7d1e"),
                            Code = "Ingredient.Delete",
                            Description = "Permite eliminar ingredientes del sistema",
                            Name = "Eliminar Ingrediente"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            Code = "Store.Create",
                            Description = "Permite crear nuevas tiendas en el sistema",
                            Name = "Crear Tienda"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            Code = "Store.Read",
                            Description = "Permite ver información de tiendas",
                            Name = "Ver Tienda"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            Code = "Store.Update",
                            Description = "Permite actualizar información de tiendas",
                            Name = "Actualizar Tienda"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                            Code = "Store.Delete",
                            Description = "Permite eliminar tiendas del sistema",
                            Name = "Eliminar Tienda"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            Code = "StoreArea.Create",
                            Description = "Permite crear nuevas áreas de tienda",
                            Name = "Crear Área de Tienda"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c"),
                            Code = "StoreArea.Read",
                            Description = "Permite ver información de áreas de tienda",
                            Name = "Ver Área de Tienda"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d"),
                            Code = "StoreArea.Update",
                            Description = "Permite actualizar áreas de tienda",
                            Name = "Actualizar Área de Tienda"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e"),
                            Code = "StoreArea.Delete",
                            Description = "Permite eliminar áreas de tienda",
                            Name = "Eliminar Área de Tienda"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f"),
                            Code = "Table.Create",
                            Description = "Permite crear nuevas mesas en el sistema",
                            Name = "Crear Mesa"
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a"),
                            Code = "Table.Read",
                            Description = "Permite ver información de mesas",
                            Name = "Ver Mesa"
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"),
                            Code = "Table.Update",
                            Description = "Permite actualizar información de mesas",
                            Name = "Actualizar Mesa"
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c"),
                            Code = "Table.Delete",
                            Description = "Permite eliminar mesas del sistema",
                            Name = "Eliminar Mesa"
                        },
                        new
                        {
                            Id = new Guid("d1a2b3c4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            Code = "Check.Create",
                            Description = "Permite crear nuevas cuentas en el sistema",
                            Name = "Crear Cuenta"
                        },
                        new
                        {
                            Id = new Guid("e2b3c4d5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            Code = "Check.Read",
                            Description = "Permite ver información de cuentas",
                            Name = "Ver Cuenta"
                        },
                        new
                        {
                            Id = new Guid("f3c4d5e6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            Code = "Check.Update",
                            Description = "Permite actualizar información de cuentas",
                            Name = "Actualizar Cuenta"
                        },
                        new
                        {
                            Id = new Guid("a4d5e6f7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                            Code = "Check.Delete",
                            Description = "Permite cancelar cuentas del sistema",
                            Name = "Eliminar Cuenta"
                        },
                        new
                        {
                            Id = new Guid("b5e6f7a8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            Code = "CheckPayment.Create",
                            Description = "Permite registrar pagos en cuentas",
                            Name = "Crear Pago"
                        },
                        new
                        {
                            Id = new Guid("c6f7a8b9-d0e1-4f2a-3b4c-5d6e7f8a9b0c"),
                            Code = "DayOpening.Create",
                            Description = "Permite registrar aperturas de día",
                            Name = "Apertura de Día"
                        },
                        new
                        {
                            Id = new Guid("d7a8b9c0-e1f2-4a3b-4c5d-6e7f8a9b0c1d"),
                            Code = "DayOpening.Read",
                            Description = "Permite ver aperturas de día",
                            Name = "Ver Apertura de Día"
                        },
                        new
                        {
                            Id = new Guid("e8b9c0d1-f2a3-4b4c-5d6e-7f8a9b0c1d2e"),
                            Code = "DayClosing.Create",
                            Description = "Permite registrar cierres de día",
                            Name = "Cierre de Día"
                        },
                        new
                        {
                            Id = new Guid("f9c0d1e2-a3b4-4c5d-6e7f-8a9b0c1d2e3f"),
                            Code = "DayClosing.Read",
                            Description = "Permite ver cierres de día",
                            Name = "Ver Cierre de Día"
                        },
                        new
                        {
                            Id = new Guid("f585a827-07a3-435f-89a0-b6734842ffea"),
                            Code = "Admin.FullAccess",
                            Description = "Acceso completo a todas las funcionalidades del sistema",
                            Name = "Acceso Total"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            Description = "Rol con acceso total al sistema",
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            Description = "Rol de administrador con acceso a gestión de usuarios y roles",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("f8109383-afb7-47a4-b97e-2f4c67c11d54"),
                            Description = "Rol básico de usuario con permisos limitados",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Roles.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("f585a827-07a3-435f-89a0-b6734842ffea")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("a5037d95-d672-4bdf-80ea-c22bc687e85f")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("4604fa93-c900-4b6e-aad2-1f424a4d3f01")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("d14e36b8-f5b7-454b-91dd-714901ce54d2")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("17c86b19-c4b0-4596-a016-cb568a343367")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("87c67f54-568a-4cbf-8992-05b4cfa20b0c")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("1d8c3417-2833-42e2-9338-2ed2ba5a3290")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("283a2cc6-3e80-41ca-90f7-227f7bcefe4c")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("8e958e23-2110-4798-b6ac-f04dd0dd156d")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("c6f7a8b9-d0e1-4f2a-3b4c-5d6e7f8a9b0c")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("d7a8b9c0-e1f2-4a3b-4c5d-6e7f8a9b0c1d")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("e8b9c0d1-f2a3-4b4c-5d6e-7f8a9b0c1d2e")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("f9c0d1e2-a3b4-4c5d-6e7f-8a9b0c1d2e3f")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("d1a2b3c4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("e2b3c4d5-f6a7-4b8c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("f3c4d5e6-a7b8-4c9d-0e1f-2a3b4c5d6e7f")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("a4d5e6f7-b8c9-4d0e-1f2a-3b4c5d6e7f8a")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("b5e6f7a8-c9d0-4e1f-2a3b-4c5d6e7f8a9b")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("a5037d95-d672-4bdf-80ea-c22bc687e85f")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("4604fa93-c900-4b6e-aad2-1f424a4d3f01")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("d14e36b8-f5b7-454b-91dd-714901ce54d2")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("1d8c3417-2833-42e2-9338-2ed2ba5a3290")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("c6f7a8b9-d0e1-4f2a-3b4c-5d6e7f8a9b0c")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("d7a8b9c0-e1f2-4a3b-4c5d-6e7f8a9b0c1d")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("e8b9c0d1-f2a3-4b4c-5d6e-7f8a9b0c1d2e")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("f9c0d1e2-a3b4-4c5d-6e7f-8a9b0c1d2e3f")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("d1a2b3c4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("e2b3c4d5-f6a7-4b8c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("f3c4d5e6-a7b8-4c9d-0e1f-2a3b4c5d6e7f")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("a4d5e6f7-b8c9-4d0e-1f2a-3b4c5d6e7f8a")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("b5e6f7a8-c9d0-4e1f-2a3b-4c5d6e7f8a9b")
                        },
                        new
                        {
                            RoleId = new Guid("f8109383-afb7-47a4-b97e-2f4c67c11d54"),
                            PermissionId = new Guid("4604fa93-c900-4b6e-aad2-1f424a4d3f01")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BiometricEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("biometric_enabled");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_confirmed");

                    b.Property<Guid?>("JobPositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_position_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_users_code");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("JobPositionId")
                        .HasDatabaseName("ix_users_job_position_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("41d21bf1-155c-43c3-8858-b5b4d047c6ed"),
                            BiometricEnabled = false,
                            Code = "ADMIN",
                            Email = "admin@example.com",
                            IsEmailConfirmed = true,
                            Name = "Admin",
                            PasswordHash = "$2a$13$PGGUsmD8GeKalR6Bizj1jO2/aaafW9pFi3D2tzllgRDiVtVwEAmFG",
                            PhoneNumber = "1234567890",
                            PublicKey = "",
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59")
                        });
                });

            modelBuilder.Entity("Domain.Entities.JobPositions.JobPosition", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("JobPositionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("JobPositionId");

                            b1.ToTable("job_positions");

                            b1.WithOwner()
                                .HasForeignKey("JobPositionId")
                                .HasConstraintName("fk_job_positions_job_positions_id");
                        });

                    b.Navigation("AuditField")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Permissions.Permission", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("PermissionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("PermissionId");

                            b1.ToTable("permissions");

                            b1.WithOwner()
                                .HasForeignKey("PermissionId")
                                .HasConstraintName("fk_permissions_permissions_id");

                            b1.HasData(
                                new
                                {
                                    PermissionId = new Guid("a5037d95-d672-4bdf-80ea-c22bc687e85f"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("4604fa93-c900-4b6e-aad2-1f424a4d3f01"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("d14e36b8-f5b7-454b-91dd-714901ce54d2"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("17c86b19-c4b0-4596-a016-cb568a343367"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("87c67f54-568a-4cbf-8992-05b4cfa20b0c"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("1d8c3417-2833-42e2-9338-2ed2ba5a3290"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("283a2cc6-3e80-41ca-90f7-227f7bcefe4c"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("8e958e23-2110-4798-b6ac-f04dd0dd156d"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("b8f1a9d4-e5c2-4a7b-9f3e-1d6c8a4b2e5f"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("c9e2b8f5-d6a3-4b8c-a0f4-2e7d9b5c3f6a"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("d0f3c9a6-e7b4-4c9d-b1e5-3f8e0c6d4a7b"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("e1a4d0b7-f8c5-4d0e-c2f6-4a9f1d7e5b8c"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("f2b5e1c8-a9d6-4e3f-b7a0-5c8d1e9f2a6b"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("a3c6f2d9-b0e7-4f8a-c1b4-6d9e2f0a3b7c"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("b4d7a3e0-c1f8-4a9b-d2c5-7e0f3a1b4c8d"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("c5e8b4f1-d2a9-4b0c-e3d6-8f1a4b2c5d9e"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("b0d3a9e6-c7f4-4a5b-d8c1-3e6f9a7b0c4d"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("c1e4b0f7-d8a5-4b6c-e9d2-4f7a0b8c1d5e"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("d2f5c1a8-e9b6-4c7d-f0e3-5a8b1c9d2e6f"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("e3a6d2b9-f0c7-4d8e-a1f4-6b9c2d0e3f7a"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("d8f1a4b5-e2c9-4d3e-f6a7-1b0c5d8e3f9a"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("e9a2b5c6-f3d0-4e4f-a7b8-2c1d6e9f4a0b"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("f0b3c6d7-a4e1-4f5a-b8c9-3d2e7f0a5b1c"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("a1c4d7e8-b5f2-4a6b-c9d0-4e3f8a1b6c2d"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("f4b7e3c0-a1d8-4e9f-b2a5-7c0d3e1f4a8b"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("a5c8f4d1-b2e9-4f0a-c3b6-8d1e4f2a5b9c"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("b6d9a5e2-c3f0-4a1b-d4c7-9e2f5a3b6c0d"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("c7e0b6f3-d4a1-4b2c-e5d8-0f3a6b4c7d1e"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("d1a2b3c4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("e2b3c4d5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("f3c4d5e6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("a4d5e6f7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("b5e6f7a8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("c6f7a8b9-d0e1-4f2a-3b4c-5d6e7f8a9b0c"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("d7a8b9c0-e1f2-4a3b-4c5d-6e7f8a9b0c1d"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("e8b9c0d1-f2a3-4b4c-5d6e-7f8a9b0c1d2e"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("f9c0d1e2-a3b4-4c5d-6e7f-8a9b0c1d2e3f"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("f585a827-07a3-435f-89a0-b6734842ffea"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                });
                        });

                    b.Navigation("AuditField")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("RoleId");

                            b1.ToTable("roles");

                            b1.WithOwner()
                                .HasForeignKey("RoleId")
                                .HasConstraintName("fk_roles_roles_id");

                            b1.HasData(
                                new
                                {
                                    RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    RoleId = new Guid("f8109383-afb7-47a4-b97e-2f4c67c11d54"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                });
                        });

                    b.Navigation("AuditField")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Roles.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.Permissions.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("Domain.Entities.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Sessions.Session", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_users_user_id");

                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("SessionId");

                            b1.ToTable("sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId")
                                .HasConstraintName("fk_sessions_sessions_id");
                        });

                    b.Navigation("AuditField")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Domain.Entities.JobPositions.JobPosition", "JobPosition")
                        .WithMany("Users")
                        .HasForeignKey("JobPositionId")
                        .HasConstraintName("fk_users_job_positions_job_position_id");

                    b.HasOne("Domain.Entities.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");

                            b1.HasData(
                                new
                                {
                                    UserId = new Guid("41d21bf1-155c-43c3-8858-b5b4d047c6ed"),
                                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                });
                        });

                    b.Navigation("AuditField")
                        .IsRequired();

                    b.Navigation("JobPosition");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.JobPositions.JobPosition", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
