// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260312233825_AddFiscalDocuments")]
    partial class AddFiscalDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.FiscalData.FiscalDataEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FiscalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fiscal_code");

                    b.Property<string>("FiscalName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fiscal_name");

                    b.HasKey("Id")
                        .HasName("pk_fiscal_data_entries");

                    b.HasIndex("FiscalCode")
                        .IsUnique()
                        .HasDatabaseName("ix_fiscal_data_entries_fiscal_code");

                    b.ToTable("fiscal_data_entries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FiscalDocuments.FiscalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Bruto")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("bruto");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("descuento");

                    b.Property<int>("DestinoVenta")
                        .HasColumnType("integer")
                        .HasColumnName("destino_venta");

                    b.Property<string>("DireccionReceptor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion_receptor");

                    b.Property<string>("DocAsociadoPreimpreso")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_asociado_preimpreso");

                    b.Property<string>("DocAsociadoSerie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_asociado_serie");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<decimal>("Exento")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("exento");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Isr")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("isr");

                    b.Property<decimal>("Iva")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("iva");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Neto")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("neto");

                    b.Property<string>("NitReceptor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nit_receptor");

                    b.Property<string>("NombreReceptor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_receptor");

                    b.Property<long?>("NumeroAcceso")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_acceso");

                    b.Property<long?>("NumeroAdmin")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_admin");

                    b.Property<string>("NumeroAutorizacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_autorizacion");

                    b.Property<decimal>("Otros")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("otros");

                    b.Property<string>("Preimpreso")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("preimpreso");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("referencia");

                    b.Property<string>("Serie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serie");

                    b.Property<string>("SerieAdmin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("serie_admin");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Tasa")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("tasa");

                    b.Property<string>("TipoVenta")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("tipo_venta");

                    b.Property<decimal>("Total")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("total");

                    b.Property<string>("XmlEnviado")
                        .HasColumnType("text")
                        .HasColumnName("xml_enviado");

                    b.HasKey("Id")
                        .HasName("pk_fiscal_documents");

                    b.HasIndex("NumeroAutorizacion")
                        .HasDatabaseName("ix_fiscal_documents_numero_autorizacion");

                    b.HasIndex("Referencia")
                        .HasDatabaseName("ix_fiscal_documents_referencia");

                    b.ToTable("fiscal_documents", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FiscalDocuments.FiscalDocumentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("discount_percentage");

                    b.Property<decimal>("ExemptAmount")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("exempt_amount");

                    b.Property<Guid>("FiscalDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_document_id");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("gross_amount");

                    b.Property<decimal>("IsrAmount")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("isr_amount");

                    b.Property<decimal>("IvaAmount")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("iva_amount");

                    b.Property<int>("MeasureUnit")
                        .HasColumnType("integer")
                        .HasColumnName("measure_unit");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("net_amount");

                    b.Property<decimal>("OtherTaxes")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("other_taxes");

                    b.Property<decimal>("Price")
                        .HasPrecision(20, 7)
                        .HasColumnType("numeric(20,7)")
                        .HasColumnName("price");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("product_code");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(20, 5)
                        .HasColumnType("numeric(20,5)")
                        .HasColumnName("quantity");

                    b.Property<string>("SaleType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("sale_type");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_fiscal_document_items");

                    b.HasIndex("FiscalDocumentId")
                        .HasDatabaseName("ix_fiscal_document_items_fiscal_document_id");

                    b.ToTable("fiscal_document_items", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.JobPositions.JobPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("HourlyCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("hourly_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_job_positions");

                    b.ToTable("job_positions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Permissions.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5037d95-d672-4bdf-80ea-c22bc687e85f"),
                            Code = "User.Create",
                            Description = "Permite crear nuevos usuarios en el sistema",
                            Name = "Crear Usuario"
                        },
                        new
                        {
                            Id = new Guid("4604fa93-c900-4b6e-aad2-1f424a4d3f01"),
                            Code = "User.Read",
                            Description = "Permite ver información de usuarios",
                            Name = "Ver Usuario"
                        },
                        new
                        {
                            Id = new Guid("d14e36b8-f5b7-454b-91dd-714901ce54d2"),
                            Code = "User.Update",
                            Description = "Permite actualizar información de usuarios",
                            Name = "Actualizar Usuario"
                        },
                        new
                        {
                            Id = new Guid("17c86b19-c4b0-4596-a016-cb568a343367"),
                            Code = "User.Delete",
                            Description = "Permite eliminar usuarios del sistema",
                            Name = "Eliminar Usuario"
                        },
                        new
                        {
                            Id = new Guid("87c67f54-568a-4cbf-8992-05b4cfa20b0c"),
                            Code = "Role.Create",
                            Description = "Permite crear nuevos roles en el sistema",
                            Name = "Crear Rol"
                        },
                        new
                        {
                            Id = new Guid("1d8c3417-2833-42e2-9338-2ed2ba5a3290"),
                            Code = "Role.Read",
                            Description = "Permite ver información de roles",
                            Name = "Ver Rol"
                        },
                        new
                        {
                            Id = new Guid("283a2cc6-3e80-41ca-90f7-227f7bcefe4c"),
                            Code = "Role.Update",
                            Description = "Permite actualizar información de roles",
                            Name = "Actualizar Rol"
                        },
                        new
                        {
                            Id = new Guid("8e958e23-2110-4798-b6ac-f04dd0dd156d"),
                            Code = "Role.Delete",
                            Description = "Permite eliminar roles del sistema",
                            Name = "Eliminar Rol"
                        },
                        new
                        {
                            Id = new Guid("a1d2e3f4-b5c6-4a7b-8d9e-0f1a2b3c4d5e"),
                            Code = "JobPosition.Create",
                            Description = "Permite crear nuevos puestos de trabajo",
                            Name = "Crear Puesto de Trabajo"
                        },
                        new
                        {
                            Id = new Guid("b2e3f4a5-c6d7-4b8c-9e0f-1a2b3c4d5e6f"),
                            Code = "JobPosition.Read",
                            Description = "Permite ver información de puestos de trabajo",
                            Name = "Ver Puesto de Trabajo"
                        },
                        new
                        {
                            Id = new Guid("c3f4a5b6-d7e8-4c9d-0f1a-2b3c4d5e6f7a"),
                            Code = "JobPosition.Update",
                            Description = "Permite actualizar puestos de trabajo",
                            Name = "Actualizar Puesto de Trabajo"
                        },
                        new
                        {
                            Id = new Guid("d4a5b6c7-e8f9-4d0e-1a2b-3c4d5e6f7a8b"),
                            Code = "JobPosition.Delete",
                            Description = "Permite eliminar puestos de trabajo",
                            Name = "Eliminar Puesto de Trabajo"
                        },
                        new
                        {
                            Id = new Guid("f585a827-07a3-435f-89a0-b6734842ffea"),
                            Code = "Admin.FullAccess",
                            Description = "Acceso completo a todas las funcionalidades del sistema",
                            Name = "Acceso Total"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            Description = "Rol con acceso total al sistema",
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            Description = "Rol de administrador con acceso a gestión de usuarios y roles",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("f8109383-afb7-47a4-b97e-2f4c67c11d54"),
                            Description = "Rol básico de usuario con permisos limitados",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Roles.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("f585a827-07a3-435f-89a0-b6734842ffea")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("a5037d95-d672-4bdf-80ea-c22bc687e85f")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("4604fa93-c900-4b6e-aad2-1f424a4d3f01")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("d14e36b8-f5b7-454b-91dd-714901ce54d2")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("17c86b19-c4b0-4596-a016-cb568a343367")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("87c67f54-568a-4cbf-8992-05b4cfa20b0c")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("1d8c3417-2833-42e2-9338-2ed2ba5a3290")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("283a2cc6-3e80-41ca-90f7-227f7bcefe4c")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("8e958e23-2110-4798-b6ac-f04dd0dd156d")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("a1d2e3f4-b5c6-4a7b-8d9e-0f1a2b3c4d5e")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("b2e3f4a5-c6d7-4b8c-9e0f-1a2b3c4d5e6f")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("c3f4a5b6-d7e8-4c9d-0f1a-2b3c4d5e6f7a")
                        },
                        new
                        {
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                            PermissionId = new Guid("d4a5b6c7-e8f9-4d0e-1a2b-3c4d5e6f7a8b")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("a5037d95-d672-4bdf-80ea-c22bc687e85f")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("4604fa93-c900-4b6e-aad2-1f424a4d3f01")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("d14e36b8-f5b7-454b-91dd-714901ce54d2")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("1d8c3417-2833-42e2-9338-2ed2ba5a3290")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("a1d2e3f4-b5c6-4a7b-8d9e-0f1a2b3c4d5e")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("b2e3f4a5-c6d7-4b8c-9e0f-1a2b3c4d5e6f")
                        },
                        new
                        {
                            RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                            PermissionId = new Guid("c3f4a5b6-d7e8-4c9d-0f1a-2b3c4d5e6f7a")
                        },
                        new
                        {
                            RoleId = new Guid("f8109383-afb7-47a4-b97e-2f4c67c11d54"),
                            PermissionId = new Guid("4604fa93-c900-4b6e-aad2-1f424a4d3f01")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BiometricEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("biometric_enabled");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_confirmed");

                    b.Property<Guid?>("JobPositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_position_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_users_code");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("JobPositionId")
                        .HasDatabaseName("ix_users_job_position_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("41d21bf1-155c-43c3-8858-b5b4d047c6ed"),
                            BiometricEnabled = false,
                            Code = "ADMIN",
                            Email = "admin@example.com",
                            IsEmailConfirmed = true,
                            Name = "Admin",
                            PasswordHash = "$2a$13$PGGUsmD8GeKalR6Bizj1jO2/aaafW9pFi3D2tzllgRDiVtVwEAmFG",
                            PhoneNumber = "1234567890",
                            PublicKey = "",
                            RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59")
                        });
                });

            modelBuilder.Entity("Domain.Entities.FiscalData.FiscalDataEntry", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("FiscalDataEntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("FiscalDataEntryId");

                            b1.ToTable("fiscal_data_entries");

                            b1.WithOwner()
                                .HasForeignKey("FiscalDataEntryId")
                                .HasConstraintName("fk_fiscal_data_entries_fiscal_data_entries_id");
                        });

                    b.Navigation("AuditField")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.FiscalDocuments.FiscalDocument", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("FiscalDocumentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("FiscalDocumentId");

                            b1.ToTable("fiscal_documents");

                            b1.WithOwner()
                                .HasForeignKey("FiscalDocumentId")
                                .HasConstraintName("fk_fiscal_documents_fiscal_documents_id");
                        });

                    b.Navigation("AuditField")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.FiscalDocuments.FiscalDocumentItem", b =>
                {
                    b.HasOne("Domain.Entities.FiscalDocuments.FiscalDocument", "FiscalDocument")
                        .WithMany("Items")
                        .HasForeignKey("FiscalDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fiscal_document_items_fiscal_documents_fiscal_document_id");

                    b.Navigation("FiscalDocument");
                });

            modelBuilder.Entity("Domain.Entities.JobPositions.JobPosition", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("JobPositionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("JobPositionId");

                            b1.ToTable("job_positions");

                            b1.WithOwner()
                                .HasForeignKey("JobPositionId")
                                .HasConstraintName("fk_job_positions_job_positions_id");
                        });

                    b.Navigation("AuditField")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Permissions.Permission", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("PermissionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("PermissionId");

                            b1.ToTable("permissions");

                            b1.WithOwner()
                                .HasForeignKey("PermissionId")
                                .HasConstraintName("fk_permissions_permissions_id");

                            b1.HasData(
                                new
                                {
                                    PermissionId = new Guid("a5037d95-d672-4bdf-80ea-c22bc687e85f"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("4604fa93-c900-4b6e-aad2-1f424a4d3f01"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("d14e36b8-f5b7-454b-91dd-714901ce54d2"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("17c86b19-c4b0-4596-a016-cb568a343367"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("87c67f54-568a-4cbf-8992-05b4cfa20b0c"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("1d8c3417-2833-42e2-9338-2ed2ba5a3290"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("283a2cc6-3e80-41ca-90f7-227f7bcefe4c"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("8e958e23-2110-4798-b6ac-f04dd0dd156d"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("a1d2e3f4-b5c6-4a7b-8d9e-0f1a2b3c4d5e"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("b2e3f4a5-c6d7-4b8c-9e0f-1a2b3c4d5e6f"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("c3f4a5b6-d7e8-4c9d-0f1a-2b3c4d5e6f7a"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("d4a5b6c7-e8f9-4d0e-1a2b-3c4d5e6f7a8b"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    PermissionId = new Guid("f585a827-07a3-435f-89a0-b6734842ffea"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                });
                        });

                    b.Navigation("AuditField")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("RoleId");

                            b1.ToTable("roles");

                            b1.WithOwner()
                                .HasForeignKey("RoleId")
                                .HasConstraintName("fk_roles_roles_id");

                            b1.HasData(
                                new
                                {
                                    RoleId = new Guid("3f039871-c926-4313-b79c-8f17e622ec59"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    RoleId = new Guid("1159c308-279e-4bba-bae2-e8063c6d908e"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                },
                                new
                                {
                                    RoleId = new Guid("f8109383-afb7-47a4-b97e-2f4c67c11d54"),
                                    CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                });
                        });

                    b.Navigation("AuditField")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Roles.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.Permissions.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("Domain.Entities.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Sessions.Session", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_users_user_id");

                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("SessionId");

                            b1.ToTable("sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId")
                                .HasConstraintName("fk_sessions_sessions_id");
                        });

                    b.Navigation("AuditField")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Domain.Entities.JobPositions.JobPosition", "JobPosition")
                        .WithMany("Users")
                        .HasForeignKey("JobPositionId")
                        .HasConstraintName("fk_users_job_positions_job_position_id");

                    b.HasOne("Domain.Entities.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.OwnsOne("Domain.ValueObjects.AuditField", "AuditField", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_created_at");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_deleted_at");

                            b1.Property<bool>("IsActive")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("audit_field_is_active");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("audit_field_updated_at");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");

                            b1.HasData(
                                new
                                {
                                    UserId = new Guid("41d21bf1-155c-43c3-8858-b5b4d047c6ed"),
                                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    IsActive = true
                                });
                        });

                    b.Navigation("AuditField")
                        .IsRequired();

                    b.Navigation("JobPosition");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.FiscalDocuments.FiscalDocument", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Entities.JobPositions.JobPosition", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
